services:
  - type: web
    name: backrooms
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    buildFilter:
      paths:
        - backend/**
      ignoredPaths:
        - src/**
        - public/**
        - '**.md'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false

