services:
  - type: web
    name: backrooms
    runtime: python
    rootDir: backend
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    buildFilter:
      paths:
        - backend/**
      ignoredPaths:
        - src/**
        - public/**
        - '**.md'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: INSTAGRAM_REDIRECT_URI
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: AWS_REGION
        sync: false

